global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['127.0.0.1:9100']

  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:9113']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '127.0.0.1:9093'

